
apiVersion: v1
kind: Service
metadata:
  name: nodejs-teste-service-app
spec:
  selector:
    app: nodejs-teste-app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 3003
  type: LoadBalancer

---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-teste-app
  labels:
    app: nodejs-teste-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-teste-app
  template:
    metadata:
      labels:
        app: nodejs-teste-app
    spec:
      containers:
      - name: nodejs-teste
        image: clsyan9/nodejs-hello-world:v1
        ports:
        - containerPort: 3003


